---
- name: provisioning ad configure k8s on vware
  hosts: localhost,all
  gather_facts: no
  tasks:
    - name: apply vm_provisioner roles
      ansible.builtin.include_role:
        name: vm_provisioner
      when: inventory_hostname == "localhost"

    - name: apply k3s_security roles
      ansible.builtin.include_role:
        name: k3s_security
      when: inventory_hostname != "localhost"

    - name: apply k3s_init roles
      ansible.builtin.include_role:
        name: k3s_init