apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-node-run
  namespace: test
spec:
  pipelineRef:
    name: node-pipeline
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: shared-storage
    - name: credenziali-git
      secret:
        secretName: ssh-git
    - name: credenziali-quay
      secret:
        secretName: flepera-quay